# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'xProContact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xProContact
    pod 'IQKeyboardManager', '4.0.13'

  target 'xProContactTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xProContactUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
